// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_4NKbI6jFbH0-LTfKyilSV8nGSJDVSZA',
    appId: '1:707682072621:web:3b5d136188426c94f260a4',
    messagingSenderId: '707682072621',
    projectId: 'food-delivery-app-eeb20',
    authDomain: 'food-delivery-app-eeb20.firebaseapp.com',
    storageBucket: 'food-delivery-app-eeb20.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyB9gkl-6ElRbF6jW8TzB52sXAUSzaJLc',
    appId: '1:707682072621:android:571a2be0174352c9f260a4',
    messagingSenderId: '707682072621',
    projectId: 'food-delivery-app-eeb20',
    storageBucket: 'food-delivery-app-eeb20.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBj4buJn9HSwAnwDt8fmDQaO4unZ4NQD9o',
    appId: '1:707682072621:ios:833096fcad1b9c08f260a4',
    messagingSenderId: '707682072621',
    projectId: 'food-delivery-app-eeb20',
    storageBucket: 'food-delivery-app-eeb20.appspot.com',
    iosBundleId: 'com.example.deliveryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBj4buJn9HSwAnwDt8fmDQaO4unZ4NQD9o',
    appId: '1:707682072621:ios:833096fcad1b9c08f260a4',
    messagingSenderId: '707682072621',
    projectId: 'food-delivery-app-eeb20',
    storageBucket: 'food-delivery-app-eeb20.appspot.com',
    iosBundleId: 'com.example.deliveryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_4NKbI6jFbH0-LTfKyilSV8nGSJDVSZA',
    appId: '1:707682072621:web:2489671a0b5efda6f260a4',
    messagingSenderId: '707682072621',
    projectId: 'food-delivery-app-eeb20',
    authDomain: 'food-delivery-app-eeb20.firebaseapp.com',
    storageBucket: 'food-delivery-app-eeb20.appspot.com',
  );
}
